language: python

python:
 - "3.6"

install: pip install -e .

script:
  - pip install -r requirements.txt

deploy:
  provider: pypi
  user: creditas
  password:
    secure: duStYAO6pqz641/zdEaumd7puSlKeACIDy36WdAPB2lmlgNASFMoxSlJHChlxUdDvNV11Ck9u9zUvnaafcbm4c16/2IovPEirvFHJNGPQZzM/mccIO2w03VvJDM3ayW/fuI5WohnukfypX3N5Sk2TgWoWqNUxTFv0q7kaHY9GUf8ynomy1lvyQ9FQMLTA/YOFS4wmLdP7zbw2X6eMA8JTyiYxJjViM1JKcA0+k0++iZ++Oz2BJ9ZlrQaAdtly2ICKN08tJiBYzZmhpinI9z3G1OVNooncZmLnT9b6QN40XwTlJQU6VRrt1Cd8MR9PtL5rJCn2cdf+dndRDA99G9YgzirSPFztPM0Tof8ExvoQgVxY+12BY0Qnyy4WvIVLsHIKifA0AnFVv4ZEw4xp9jEvU6azWGWTHAzrDHkLGXNxHKw+2emZUGJBuuNEQjc2kODMgB+OcHcxbmfNlmQdyTpn6NMxbtI9MjiIEPYyiBMLqs3cP2FHNCdNCHyPdr1BZG6p6AfsbYpYM82dwyS110g4I3gSAa3+9DPWtti/GfypV9/03+Y72iXbGwD8l6SVjH4Vl9CNHmlbh31XkxDv+lMu/m/+91Eu19frGNlhKLZNETNVCJxAiYYwddfR9KSJn7/0v7U4WtbBcJCuvP/H7UrG3/RG7RoWc5bReI6ojjK1us=
  on:
    branch: master
