language: python

python:
 - "3.6"

install: pip install -e .

script:
  - pip install -r requirements.txt

deploy:
  provider: pypi
  user: creditas
  password:
    secure: "scITcpqiQQwQFJDpK0l7aF0aGKzJLQquonS6dB+n4mNLxCy8bsqWHHpyKbqDJ3KFO/J+O43LPlhFWr3Vnn77O9iOo1v7obxSvLoQ6zgk5A3/Gi8qhC5SSBSi45hVjzLMxPc8TtbiFqJly8Q8wjZuRX8lZB9utm3mXbDLtOo8jaahGkIC8n2lFenJZiZWl9n6pbZcNtBOQGYO8OudkkDOW0TDyDbhmEAXbj0NT+LQS5x92bU07fequywDciDFuyCqP373vgkk++mNxFhIHzw3ly+FKWmx+8zr8L92xoDw5c/6NkIC5sW/xIf24b/L6GuG4uj8yfqxThNOQYMj5lohK4QlehwzrlYIBFxhEU6t8r6l9kmCCUp2pvkZNkzlc6BBglpP5ZG4vRZnm4WBfhIVVfNBzQlvFPUDvUKG/X4qGFz64Om+P3FcFyg3rK2ftXOh0GUSbY6565NmCUxDbEW7/HOyHgboNSjlI8PKcXpGoG662aR7GX2Cvdm/zo4t9gtXblpjRG6TEzXTzIjo2Su1VCyugY82OWCL4bfGCCZxQGP7VjXU4Q6Gp12lcjIto1auQIK97hHqYhIxULs4aI4nUX3Z+rMVC9I5ozhAVpsW1PKM+/q0cQR5YYbdzO/Tj6jQLHm0ncy+HK/8pEYyai+EHPnlmsE9ETxVEqoiMPmnbp0="
  on:
    branch: master
